### ISSUE TITLE
Creating Octomap from PointCloud

### ISSUE THREAD

**Issue by boonflies** [ethz-asl/point_cloud_io#7]
I found that using moveit-RViz, octomaps can be generated with a robot fitted with depth camera publishing its pointcloud.

I am trying to generate the same scenario but instead of using the pointcloud from depth camera, I want to use the pointcloud published by ply_publisher (.ply is generated using LSD_SLAM algorithm). But unlike the depth camera which has a transform, the sensor_frame of ply_publisher does not have a transform. 

So, is it possible to publish the ply_publisher pointcloud as though the depth camera in the robot is publishing the pointcloud? Is my method of generating octomaps correct?

**Comment by pfankhauser** [comment]
You can use the `_frame:=/sensor_frame` parameter to publish the point clouds in a given frame. Now you only need the publish the corresponding TF, and your setup should work.
